import type { PlanCatalogItem } from '../customer/api/plans';

/** Mirrors backend `PLAN_CATALOG_DEFAULTS` — used when GET /plans/catalog is unavailable. */
export const MARKETING_PLAN_CATALOG_FALLBACK: PlanCatalogItem[] = [
  {
    id: 'marketing-fallback-essential',
    slug: 'essential',
    name: 'Essential',
    tagline: 'Protection',
    positioning: 'Protection',
    maxAssets: 5,
    maxUsers: 1,
    monthlyAmountCents: 19_900,
    currency: 'ZAR',
    isCustomPricing: false,
    isMostPopular: false,
    isActive: true,
    sortOrder: 1,
    supportLevel: 'standard',
    features: [
      'Up to 5 registered assets',
      'Customer mobile app',
      'Basic asset management',
      'Protection and insurance services',
      'GPS-assisted recovery when a compatible tracking device is connected',
      'Standard notifications',
      'Standard customer support',
    ],
    accountTypes: ['both'],
  },
  {
    id: 'marketing-fallback-plus',
    slug: 'plus',
    name: 'Plus',
    tagline: 'Protection + Monitoring',
    positioning: 'Protection + Monitoring',
    maxAssets: 10,
    maxUsers: 1,
    monthlyAmountCents: 39_900,
    currency: 'ZAR',
    isCustomPricing: false,
    isMostPopular: true,
    isActive: true,
    sortOrder: 2,
    supportLevel: 'priority',
    features: [
      'Everything in Essential',
      'Up to 10 registered assets',
      'Enhanced GPS monitoring',
      'GPS alerts',
      'Location history',
      'Incident reporting and management',
      'Priority support',
      'Enhanced notifications',
      'Call centre assistance',
    ],
    accountTypes: ['both'],
  },
  {
    id: 'marketing-fallback-pro',
    slug: 'pro',
    name: 'Pro',
    tagline: 'Protection + Advanced Monitoring + Priority Service',
    positioning: 'Protection + Advanced Monitoring + Priority Service',
    maxAssets: 25,
    maxUsers: 5,
    monthlyAmountCents: 69_900,
    currency: 'ZAR',
    isCustomPricing: false,
    isMostPopular: false,
    isActive: true,
    sortOrder: 3,
    supportLevel: 'enhanced',
    features: [
      'Everything in Plus',
      'Up to 25 registered assets',
      'Advanced GPS monitoring',
      'Extended location and activity history',
      'Advanced alerts',
      'Priority incident handling',
      'Advanced reporting',
      'Multiple users',
      'Enhanced customer support',
    ],
    accountTypes: ['both'],
  },
  {
    id: 'marketing-fallback-business',
    slug: 'business',
    name: 'Business',
    tagline: 'Complete Business Platform',
    positioning: 'Complete Business Platform',
    maxAssets: null,
    maxUsers: null,
    monthlyAmountCents: null,
    currency: 'ZAR',
    isCustomPricing: true,
    isMostPopular: false,
    isActive: true,
    sortOrder: 4,
    supportLevel: 'dedicated',
    features: [
      '25+ assets with custom limits',
      'Multiple users and locations',
      'Advanced monitoring',
      'Admin Dashboard functionality',
      'Security Dashboard functionality',
      'Call Centre functionality',
      'Advanced reporting and custom workflows',
      'Dedicated account support',
      'Custom integrations and API access where applicable',
    ],
    accountTypes: ['business'],
  },
];
