/**
 * Token generation/hashing primitives shared by every token-shaped artifact
 * in Feature 001 (refresh tokens, enrollment tickets, reset-MFA-verification
 * tokens, invitation tokens).
 *
 * security-review.md §6: "Refresh-token generation & storage — >=32 bytes
 * from a CSPRNG, base64url; stored as SHA-256 of the token." The same
 * reasoning (high-entropy random value, not a low-entropy secret like a
 * password) is ratified for every other single-use token this feature
 * mints — none of them are passwords, so none of them go through a
 * per-request KDF (bcrypt/argon2 would be cost without benefit here).
 */
import { randomBytes, createHash, timingSafeEqual } from 'node:crypto';

/** >=32 bytes CSPRNG, base64url-encoded — the ratified shape for every
 * opaque single-use token this feature mints. */
export function generateOpaqueToken(byteLength = 32): string {
  if (byteLength < 32) {
    throw new Error(`[lib/crypto] generateOpaqueToken byteLength must be >= 32, got ${byteLength}`);
  }
  return randomBytes(byteLength).toString('base64url');
}

/** SHA-256 hex digest — the ratified at-rest form for every opaque token
 * above. Never used for passwords (Supabase/GoTrue owns password hashing). */
export function sha256Hex(value: string): string {
  return createHash('sha256').update(value, 'utf8').digest('hex');
}

/** Constant-time comparison for cases where two hashes/tokens are compared
 * outside of a database unique-index lookup (defence in depth against a
 * timing side-channel; the primary lookup mechanism is always an indexed
 * equality query, not this function, which is best-effort where used). */
export function safeEqual(a: string, b: string): boolean {
  const bufA = Buffer.from(a, 'utf8');
  const bufB = Buffer.from(b, 'utf8');
  if (bufA.length !== bufB.length) {
    return false;
  }
  return timingSafeEqual(bufA, bufB);
}

/** A 6-digit numeric TOTP-style code is never generated by this backend —
 * that belongs to Supabase/GoTrue's own TOTP factor implementation. This
 * module intentionally contains no OTP-generation logic. */
